/**
 * The doris GPU-sharing protocol (the owner's own instruction, this
 * checkpoint's session): doris can hold only one big model at a time, so
 * every run records what `/api/ps` showed loaded at start and end, in the
 * transcript's own header/footer -- never edited in after the fact, always
 * generated by the run itself. Kept in its own module (no side effects at
 * import time) so it can be unit tested without importing `checkpoint.ts`,
 * whose own top-level code sets `DMCP_DB_PATH` and calls `main()`.
 */
export interface OllamaLoadedModel {
  name: string;
  size: number;
  size_vram: number;
  expires_at: string;
}

export interface OllamaPsResponse {
  models: OllamaLoadedModel[];
}

/** Pure formatting -- no network, no side effects, so it is testable in
 *  isolation from the actual `/api/ps` call. */
export function summarizeLoadedModels(data: OllamaPsResponse): string {
  if (data.models.length === 0) return "(no models loaded)";
  return data.models
    .map((m) => `${m.name} (size_vram=${m.size_vram}, expires_at=${m.expires_at})`)
    .join(", ");
}

/** `baseUrl` is the OpenAI-compatible `/v1` URL this repository already
 *  uses (`PRISONER_MODEL_URL`); Ollama's own `/api/ps` lives at the root,
 *  one level up. Never throws -- a GPU-status check failing must not abort
 *  a real run, it should simply say so in the transcript. */
export async function fetchLoadedModelsSummary(baseUrl: string, fetchFn: typeof fetch = fetch): Promise<string> {
  const opsUrl = `${baseUrl.replace(/\/v1\/?$/, "")}/api/ps`;
  try {
    const response = await fetchFn(opsUrl);
    if (!response.ok) {
      return `(could not query /api/ps: HTTP ${response.status})`;
    }
    const data = (await response.json()) as OllamaPsResponse;
    return summarizeLoadedModels(data);
  } catch (err) {
    return `(could not query /api/ps: ${err instanceof Error ? err.message : String(err)})`;
  }
}
